### ISSUE TITLE
ModuleNotFoundError: No module named 'cmp.stages.eeg'

### ISSUE THREAD

**Issue by jsheunis** [connectomicslab/connectomemapper3#160] opened 2022-04-08 10:04 UTC
_Issue related to JOSS review: https://github.com/openjournals/joss-reviews/issues/4248_

I get the following error when running `cmpbidsappmanager` from the conda environment `py37cmp-gui` that was created with `conda env create -f environment_macosx.yml` (and after creation running `pip install connectomemapper`). This prevents the GUI from opening.

```
(py37cmp-gui) ➜  ~ cmpbidsappmanager
Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/py37cmp-gui/bin/cmpbidsappmanager", line 5, in <module>
    from cmp.cli.cmpbidsappmanager import main
  File "/Users/jsheunis/opt/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/cli/cmpbidsappmanager.py", line 21, in <module>
    import cmp.bidsappmanager.gui.principal
  File "/Users/jsheunis/opt/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/bidsappmanager/gui/principal.py", line 21, in <module>
    import cmp.project
  File "/Users/jsheunis/opt/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/project.py", line 25, in <module>
    from cmp.pipelines.functional import eeg as EEG_pipeline
  File "/Users/jsheunis/opt/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/pipelines/functional/eeg.py", line 17, in <module>
    from cmp.stages.eeg.inverse_solution import EEGInverseSolutionStage
ModuleNotFoundError: No module named 'cmp.stages.eeg'
```

More info:
- macOS Big Sur 11.2.3
- conda 4.9.2
- Python 3.7.12

**Comment by sebastientourbier** [comment] 2022-04-11 08:37
Dear @jsheunis,

I am sorry to hear you encountered this issue. 

Indeed, this has been recently reported in #150  and the cause has been identified.

Briefly, CMP3 is using two different setup.py files:

-  https://github.com/connectomicslab/connectomemapper3/blob/master/setup.py installs CMP3 with all data resources (such as atlas images). It is used during development and for installing CMP3 in the BIDS App (docker image).
-  https://github.com/connectomicslab/connectomemapper3/blob/master/setup_pypi.py is a lightweight installation of CMP3 (no data resources) that allows us to make python package < 100MB, the limit on the Python Index Package manager (pip). It is used to create and publish the package to pip.

But I did found that cmp.stages.eeg was missing in the package list of https://github.com/connectomicslab/connectomemapper3/blob/master/setup_pypi.py... 

While this will be fixed in the next release, there still exists a solution in the meantime: to use [setup.py](https://github.com/connectomicslab/connectomemapper3/blob/master/setup.py) that list all packages properly. Having the `py37cmp-gui` environment activated, this can be done as follows:

```
$ pip uninstall connectomemapper
$ pip install git+https://github.com/connectomicslab/connectomemapper3.git@v3.0.3
```

**Closed** 2022-04-13 07:15 UTC
Labels: bug
